

CREATE TABLE PESSOA_FISICA (
	ID_CLIENTE_PF INTEGER PRIMARY KEY NOT NULL,
	NOME VARCHAR2(40) NULL,
	RG VARCHAR2(10) NOT NULL,
	CPF VARCHAR2(11) NOT NULL,
	ORGAO_EMISSOR_RG VARCHAR2(10) NULL,
	TELEFONE VARCHAR2(20) NULL,
	EMAIL VARCHAR2(20) NULL,
	NUMERO_CONTA iNTEGER NULL, 
	DATA_NASCIMENTO DATE NULL,
	ID_ENDERECO INTEGER NULL,
)	
/

CREATE TABLE PESSOA_JURIDICA (
	ID_CLIENTE_PJ INTEGER PRIMARY KEY NOT NULL,
	NOME_FANTASIA VARCHAR2(40) NULL,
	CNPJ VARCHAR2(14) NOT NULL,
	INSCRICAO_ESTADUAL VARCHAR2(40) NULL,
	INSCRICAO_MUNICIPAL VARCHAR2(40) NULL,
	VALIDADE_INSCRICAO_ESTADUAL DATE NULL,
	ID_ENDERECO INTEGER NULL,
	FAX VARCHAR2(20) NULL
)
/	
	
CREATE TABLE ENDERECO (
	ID_ENDERECO INTEGER PRIMARY KEY NOT NULL,
	RUA VARCHAR2(50) NULL,
	NUMERO INTEGER NULL,
	COMPLEMENTO VARCHAR2(50) NULL,
	BAIRRO VARCHAR2(50) NULL,
	CIDADE VARCHAR2(20) NULL,
	UF VARCHAR2(2) NULL,
	CEP VARCHAR2(9) NULL
)
/

CREATE TABLE CONTA_CLIENTE (
	ID_CONTA_CLIENTE INTEGER PRIMARY KEY NOT NULL,
	ID_CLIENTE INTEGER NULL,
	NUMERO INTEGER NULL,
	SALDO_ATUAL NUMBER(10,2) NULL,
	DATA_ATUALIZACAO DATE NULL,
	CD_MOV INTEGER NULL
)
/

CREATE TABLE MOV_CLIENTES (
	ID_MOVIMENTACAO INTEGER PRIMARY KEY NOT NULL,
	DATA_MOVIMENTACAO DATE NULL,
	TP_MOV VARCHAR2(1) NULL,
	VALOR_MOV NUMBER(10,2) NULL,
	ID_CONTA_CLIENTE INTEGER NULL,
	NUMERO_CONTA INTEGER NULL,
	)
/

		
		
CREATE SEQUENCE ID_CLIENTE_PF START WITH 1;  
/
CREATE SEQUENCE ID_CLIENTE_PJ START WITH 1;   
/
CREATE SEQUENCE ID_ENDERECO START WITH 1;  
/
CREATE SEQUENCE ID_CONTA_CLIENTE START WITH 1;  
 /
CREATE SEQUENCE ID_MOVIMENTACAO START WITH 1; 
/
 